### ISSUE TITLE
Data Visualization using Elasticsearch Datastore

### ISSUE THREAD

**Issue by 0x48piraj** [saeeddhqan/Maryam#182]
Web interface dashboard that allows observation of an active engagement. Data visualization would include, but not be limited to: host node graph with activity indicators and heat maps.

Writing the output to Elasticsearch. Exploring and performing data visualization using Kibana.

**Comment by saeeddhqan** [comment]
This is a suggestion?

**Comment by 0x48piraj** [comment]
Yes, and if you deem the idea fit, I'll like to implement it as well.

**Comment by saeeddhqan** [comment]
any demo?

**Comment by 0x48piraj** [comment]
Currently, the web interface is not developed, so, I can write quick code to demo the functionality with mock data, will that be fine?

**Comment by saeeddhqan** [comment]
Yes.

**Comment by anuran-roy** [comment]
Uhh... I have worked a bit with ElasticSearch and ELK Stack as a whole. Maybe it's only with me, I won't recommend it to be honest. It will bloat the size of the dependencies for Maryam. 
Also, setting up ElasticSearch is a pain. So I think we'd rather go for some other alternatives... 😅 

@saeeddhqan What do you think?

**Comment by 0x48piraj** [comment]
When you say dependencies, what do you mean by that?

Also, if not ELK stack, do you have any other alternative in mind?

**P.S.** Elasticsearch 7.x is so easy to setup, it now ships with Java bundled.

**Comment by 0x48piraj** [comment]
There are architecture types which ELK stack can offer, we can go with a simple architecture as below,

![image](https://user-images.githubusercontent.com/5800726/114884166-2c58e780-9e23-11eb-83a6-15a7d9ab2789.png)

Or, for handling more complex pipelines built for handling large amounts of data in production, additional components are likely to be added into your logging architecture, for resiliency,

![image](https://user-images.githubusercontent.com/5800726/114884347-54484b00-9e23-11eb-94d6-26d6c39376d5.png)

In case of Maryam, I think the prior architecture will yield desired results.

**Comment by 0x48piraj** [comment]
Maryam is a tool which aids in OSINT. OSINT is majorly about gathering information and building meaningful connections which can yield results. Depicting connections is usually done using graphs.

Graph databases are a family of NoSQL databases, based on the concept of modelling your data as a graph, i.e. a collection of nodes (representing entities) and edges (representing relationships).

So, we can use graph databases such as Neo4j. As per it's website states "Neo4j is a native graph database, built from the ground up to leverage not only data but also data relationships.".

I have worked previously with Python + Neo4j on an OSINT personal project visualising usernames on different social media websites. So, that's an alternative too. What do you think @saeeddhqan?

**Comment by anuran-roy** [comment]
Sorry for barging in... 😅 
I think that Neo4j will be a better choice tbf. I haven't used, but we surely do need to establish relatiionships between data as well 😅 

Also, I feel that this should be an extension, not in the mail tool itself. Because otherwise, the size of Maryam will considerably increase.

**Comment by 0x48piraj** [comment]
The web interface will be built seperately. Saeed has already discussed this over the Slack channel.

**Comment by necrose99** [comment]
https://girishsaraf03.medium.com/getting-started-with-elasticsearch-using-python-flask-part-1-8a45235b660
https://www.techchorus.net/blog/logging-from-flask-application-to-elasticsearch-via-logstash/ 
https://medium.com/@huseinzolkepli/elk-for-flask-bc486d58deb3 
https://pypi.org/project/python-logstash-async/

**https://pypi.org/project/Flask-Elastic/ , elasticsearch-kibana-cli** 
**https://pypi.org/project/Flask-Graphite/** might offer a few options ,  (Grafana dashboard) <img alt="An example dashboard powered with Flask-Graphite" src="https://flask-graphite.readthedocs.io/en/latest/_images/grafana_dashboard.png" />
 https://flask-graphite.readthedocs.io/en/latest/

**flask is already a dependency** 
extensions without much bloat..  if the back ends are there great use them else cli is fine for average pentester 
however managers and reports.... of how much is leeking....

just adding a layer of querying to flask+elk  or otherwise lightweight graphing etc... might be doable without too much bloat. and minimalismus..  push/pull graphic .. on the fly ...

while this is way to much python for my novice hide , hopefully few bits of research on offer hear has a few uses...
it is quite well beyond sysadmin or simple scripts.

Good luck...
and always happy to FWD this as a Talk to Dallas OWASP ...

**Comment by necrose99** [comment]
@saeeddhqan https://github.com/qeeqbox/chameleon  might have similar elements.
